image: maven:3.3.9-jdk-8
stages:
   - auto-merge

auto-merge:
  stage: auto-merge
  image: 10.0.14.54:5005/auto-merge/py:3.7
  variables:
    srbranch: $CI_COMMIT_BRANCH
    CI_USER_TOKEN: _1rS7dhCr-smfBWtAC7m
    CI_REPOSITORY_URL: http://gitlab-ci-token:$CI_USER_TOKEN@10.0.0.15/$CI_PROJECT_PATH.git
  tags:
    - 90-sixdee-am
  rules:
    - if: ' $CI_COMMIT_BRANCH !~ /feature|maintenance|hotfix/ && $CI_COMMIT_BRANCH=~ /.*/ && $CI_PIPELINE_SOURCE != "merge_request_event" '
  script:
    - python3 $CI_PROJECT_DIR/auto-merge/csvparse.py $CI_COMMIT_BRANCH $CI_REPOSITORY_URL $CI_JOB_URL $CI_PIPELINE_URL $CI_SERVER_URL $CI_PROJECT_URL $CI_JOB_ID $CI_JOB_NAME $CI_PROJECT_ID $CI_PROJECT_DIR